# Generated by Django 5.2.4 on 2025-07-18 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_app', '0002_question_tag_lesson_answer_course_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AlterField(
            model_name='course',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='courses', to='education_app.tag'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='questions', to='education_app.question'),
        ),
    ]
