# Generated by Django 5.2.4 on 2025-07-09 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название курса')),
                ('description', models.TextField(null=True, verbose_name='Описание курса')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='course_avatars/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duration_days', models.PositiveIntegerField(default=30, verbose_name='Длительность курса (в днях)')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время окончания курса')),
                ('chat', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course', to='chat.chat')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='module_avatars/')),
                ('title', models.CharField(max_length=50, verbose_name='Название модуля')),
                ('content', models.TextField(verbose_name='Содержимое модуля')),
                ('order', models.PositiveIntegerField(default=0, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='course.course')),
            ],
        ),
    ]
